/**
 * Heap analytics event constants for the RIA Chatbot.
 */
export const HEAP_RIA_CHATBOT_EVENTS = {
  CLICK_ON_CHATBOT_ICON: "app_ria_chatbot_click_on_chatbot_icon",
  CHAT_WITH_US_MODAL_OPENED: "app_ria_chatbot_chat_with_us_modal_opened",
  CHAT_WITH_US_MODAL_CLOSED: "app_ria_chatbot_chat_with_us_modal_closed",
  SEARCH_FROM_CHATBOT: "app_ria_chatbot_search_from_chatbot",
  EXHAUSTED_10_ATTEMPTS_FOR_TOKEN: "app_ria_chatbot_exhausted_10_attempts_for_token",
  LIVEKIT_TOKEN_GENERATED: "app_ria_chatbot_livekit_token_generated",
  LIVEKIT_TOKEN_GENERATION_FAILED: "app_ria_chatbot_livekit_token_generation_failed",
  CONNECTED_TO_LIVEKIT_ROOM: "app_ria_chatbot_connected_to_livekit_room",
  FAILED_TO_CONNECT_TO_LIVEKIT_ROOM: "app_ria_chatbot_failed_to_connect_to_livekit_room",
  DISCONNECTED_FROM_LIVEKIT_ROOM: "app_ria_chatbot_disconnected_from_livekit_room",
  MESSAGE_LIKES_AND_DISLIKES: "app_ria_chatbot_message_likes_and_dislikes",
  MESSAGE_LIKES_AND_DISLIKES_FAILED: "app_ria_chatbot_message_likes_and_dislikes_failed",
  CONTEXT_RECEIVED: "app_ria_chatbot_context_received",
  MESSAGE_SENT: "app_ria_chatbot_message_sent",
  MESSAGE_SEND_FAILED: "app_ria_chatbot_message_send_failed",
  MESSAGE_RECEIVED: "app_ria_chatbot_message_received",
  CONTEXT_POSTED_TO_ROOM: "app_ria_chatbot_context_posted_to_room",
  FAILED_TO_POST_CONTEXT_TO_ROOM: "app_ria_chatbot_failed_to_post_context_to_room",
  TEXT_POSTED_TO_ROOM: "app_ria_chatbot_text_posted_to_room",
  LIVE_AGENT_HANDOFF: "app_ria_chatbot_agent_handoff",
  LIVE_AGENT_HANDOFF_CONNECTED: "app_ria_chatbot_agent_handoff_connected",
  LIVE_AGENT_HANDOFF_DISCONNECTED: "app_ria_chatbot_agent_handoff_disconnected",
  LIVE_AGENT_HANDOFF_CLOSED_BY_USER: "app_ria_chatbot_agent_handoff_closed_by_user",
  LIVE_AGENT_SEND_MESSAGE_TO_USER: "app_ria_chatbot_agent_send_message_to_user",
  USER_RECEIVED_MESSAGE_FROM_LIVEAGENT: "app_ria_chatbot_user_receive_message_from_liveagent",
  LIVE_AGENT_HANDOFF_CONVERSATION_RESOLVED: "app_ria_chatbot_agent_handoff_conversation_resolved",
  LIVE_AGENT_HANDOFF_CONNECTION_FAILED: "app_ria_chatbot_agent_handoff_connection_failed",
  CHATWOOT_WEBSOCKET_CLOSED: "app_ria_chatbot_chatwoot_websocket_closed",
  CHATWOOT_WEBSOCKET_ERROR: "app_ria_chatbot_chatwoot_websocket_error",
  CHATWOOT_STATUS: "app_ria_chatbot_chatwoot_status",
  IDLE_SESSION_TERMINATED: "app_ria_chatbot_idle_session_terminated",
  NO_MESSAGE_RECEIVED_IN_10S: "app_ria_chatbot_no_message_received_in_10s",
  NO_MESSAGE_RECEIVED_IN_20S: "app_ria_chatbot_no_message_received_in_20s",
  NO_MESSAGE_RECEIVED_IN_30S: "app_ria_chatbot_no_message_received_in_30s",
  RECONNECTED_TO_LIVEKIT_ROOM: "app_ria_chatbot_reconnected_to_livekit_room",
} as const;
